AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Serverless Load Service

Globals:
  Function:
    Timeout: 300

Resources:
  InventoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.handler
      Runtime: python3.9
      Timeout: 900
      Events:
        Inventory:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
