"""create load_jobs table

Revision ID: 980f67672df7
Revises: 
Create Date: 2024-07-04 15:04:59.529081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '980f67672df7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('load_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transform_job_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=True),
    sa.Column('data', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_load_jobs_transform_job_id'), 'load_jobs', ['transform_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_load_jobs_transform_job_id'), table_name='load_jobs')
    op.drop_table('load_jobs')
    # ### end Alembic commands ###
